import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

interface InitOptions {
  force?: boolean;
  template?: string;
}

export async function initCommand(options: InitOptions): Promise<void> {
  const configPath = path.resolve(process.cwd(), "vault.config.ts");

  try {
    // Check if file already exists
    if (!options.force) {
      try {
        await fs.access(configPath);
        console.error(
          "❌ vault.config.ts already exists. Use --force to overwrite.",
        );
        process.exit(1);
      } catch {
        // File doesn't exist, continue
      }
    }

    // Get template content
    const templateContent = await getTemplateContent(
      options.template || "basic",
    );

    // Write configuration file
    await fs.writeFile(configPath, templateContent, "utf-8");

    console.log("✅ vault.config.ts created successfully!");
    console.log(`📁 Location: ${configPath}`);
    console.log("");
    console.log("Next steps:");
    console.log("1. Review and customize the configuration");
    console.log("2. Set your environment variables");
    console.log("3. Import and use createVaultClient() in your code");
  } catch (error) {
    console.error("❌ Failed to create vault.config.ts:", error);
    process.exit(1);
  }
}

async function getTemplateContent(_templateType: string): Promise<string> {
  const templatePath = path.join(
    __dirname,
    "..",
    "..",
    "..",
    "vault.config.ts",
  );

  try {
    // Use the existing vault.config.ts as template
    const content = await fs.readFile(templatePath, "utf-8");

    // Adjust imports for user's project
    const adjustedContent = content
      .replace(
        /from "\.\/src\/core\/config\.types\.js";/g,
        'from "@aether-vault/node/src/core/config.types.js";',
      )
      .replace(/from "\.\/\.\.\/\.\./g, 'from "@aether-vault/node');

    return adjustedContent;
  } catch (error) {
    // Fallback to basic template
    return getBasicTemplate();
  }
}

function getBasicTemplate(): string {
  return `/**
 * Aether Vault Configuration
 * 
 * Generated by aether-vault CLI
 */

import {
  VaultConfigFile,
  CompleteVaultConfig,
  Environment,
  AuthMethod,
  LogLevel,
  ExtendedAuthConfig,
} from "@aether-vault/node/src/core/config.types.js";

/**
 * Authentication configuration
 */
function getAuthConfig(): ExtendedAuthConfig {
  const authMethod = (process.env.VAULT_AUTH_METHOD as AuthMethod) || "token";

  switch (authMethod) {
    case "token":
      return {
        method: "token",
        token: process.env.VAULT_TOKEN || "your-vault-token-here",
      };
    
    default:
      throw new Error(\`Unsupported auth method: \${authMethod}\`);
  }
}

/**
 * Default configuration
 */
const defaultConfig: CompleteVaultConfig = {
  endpoint: process.env.VAULT_ENDPOINT || "https://vault.skygenesisenterprise.com/api/v1",
  auth: getAuthConfig(),
  retry: {
    retries: 3,
    delay: 1000,
    backoff: true,
    maxDelay: 10000,
  },
  logging: {
    level: (process.env.VAULT_LOG_LEVEL as LogLevel) || "info",
    console: true,
    http: false,
  },
  features: {
    autoRenewToken: false,
    auditEnabled: false,
    metricsEnabled: false,
    cachingEnabled: true,
    tracingEnabled: false,
  },
  timeout: 30000,
  apiVersion: "v1",
};

/**
 * Environment-specific configurations
 */
const environments: Record<Environment, Partial<CompleteVaultConfig>> = {
  development: {
    endpoint: "http://localhost:8200/api/v1",
    auth: {
      method: "token",
      token: "dev-token",
    },
    logging: {
      level: "debug",
      console: true,
      http: true,
    },
  },
  
  production: {
    logging: {
      level: "warn",
      console: false,
    },
    retry: {
      retries: 5,
      delay: 2000,
    },
    features: {
      autoRenewToken: true,
      auditEnabled: true,
    },
  },
  
  test: {
    endpoint: "http://localhost:8200/api/v1",
    auth: {
      method: "token",
      token: "test-token",
    },
    logging: {
      level: "error",
      console: false,
    },
    retry: {
      retries: 0,
    },
  },
};

export const vaultConfig: VaultConfigFile = {
  default: defaultConfig,
  environments,
};

export default vaultConfig;
`;
}
